- id: "1610397333292"
  alias: morgenlys
  description: ""
  trigger:
    - platform: time
      at: 06:30
  condition: []
  action:
    - scene: scene.morgenlys
  mode: single
- id: "1610397407800"
  alias: dagslys
  description: ""
  trigger:
    - platform: time
      at: 07:10:00
  condition: []
  action:
    - scene: scene.dagslys
  mode: single
- id: "1610397477978"
  alias: kveldslys
  description: ""
  trigger:
    - platform: time_pattern
      hours: "17"
      minutes: "30"
      seconds: "00"
  condition: []
  action:
    - scene: scene.kveldslys
  mode: single
- id: "1610397542731"
  alias: nattlys
  description: ""
  trigger:
    - platform: time_pattern
      hours: "18"
      minutes: "30"
      seconds: "0"
  condition: []
  action:
    - scene: scene.nattlys
  mode: single
- id: steppers
  alias: Write Stepper Value to ESP
  trigger:
    - platform: state
      entity_id: input_number.stepper_control
  action:
    - service: esphome.testnode_control_stepper
      data_template:
        target: "{{ trigger.to_state.state | int }}"
- alias: Write Stepper Speed to ESP
  trigger:
    - platform: state
      entity_id: input_number.stepper_speed
  action:
    - service: esphome.testnode_control_stepperspeed
      data_template:
        speed: "{{ trigger.to_state.state | int }}"
  id: aecc05dc804e4ad197fcd3c872f77411
- id: "1611061943338"
  alias: Batteri tesla
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.flyet_battery_sensor
      below: "46"
  condition: []
  action:
    - service: notify.telegramnotification
      data:
        title: "*Teslaen bør lades*"
        message: Bateriet på teslaen er {{states('sensor.flyet_battery_sensor') }}%
  mode: single
- id: "1611686228332"
  alias: Oppdatere villavent nivå
  description: ""
  trigger:
    - platform: state
      entity_id: input_number.villavent_viftehastighet
  condition: []
  action:
    - service: modbus.write_register
      data:
        hub: hub1
        address: 100
        unit: 1
        value: "{{ trigger.to_state.state | int }}"
  mode: single
- id: a5fccdfcd9c44ae29665cbfce0cb6461
  alias: Doorbell
  trigger:
    - platform: state
      entity_id: switch.doorbell
      to: "on"
  action:
    - service: notify.mobile_app_gunnar_s10
      data:
        title: Doorbell
        message: Someone is at the door!
    - service: notify.telegramnotification
      data:
        title: "*Ding dong*"
        message: Det ringer på!
    - service: switch.turn_off
      target:
        entity_id: switch.doorbell
  mode: single
- id: "1613136332366"
  alias: Varsle villavent
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.vifteniva
      above: "1"
      for: "3600"
  condition: []
  action:
    - service: notify.telegramnotification
      data:
        title: "*Ventilasjonen går og går*"
        message: Ventilasjonen er på nivå {{states('sensor.vifteniva') }}
  mode: single
- id: "1614538952193"
  alias: "Oppdatere villavent temp nivå "
  description: ""
  trigger:
    - platform: state
      entity_id: input_number.villavent_temperaturniva
  condition: []
  action:
    - service: modbus.write_register
      data:
        hub: hub1
        address: 206
        unit: 1
        value: "{{ trigger.to_state.state | int }}"
  mode: single
- id: "1618555616767"
  alias: Nattsenking bad
  description: ""
  trigger:
    - platform: time
      at: 07:00
  condition: []
  action:
    - type: turn_on
      device_id: 8ff74c17b2ef9164911c738e639bc972
      entity_id: switch.bad1etg
      domain: switch
  mode: single
- id: "1618555638285"
  alias: Nattsenking bad av
  description: ""
  trigger:
    - platform: time
      at: "19:00"
  condition: []
  action:
    - type: turn_off
      device_id: 8ff74c17b2ef9164911c738e639bc972
      entity_id: switch.bad1etg
      domain: switch
  mode: single
- id: "1618649105770"
  alias: NMS Referatvarsling
  description: ""
  trigger:
    - platform: state
      entity_id: sensor.siste_nms_referat
  condition: []
  action:
    - service: notify.telegramnotification
      data:
        title: "*NMS GL Referat oppdatert*"
        message: "Siste referat: {{states('sensor.siste_nms_referat') }}"
  mode: single
- id: "1623495484193"
  alias: Ventilere 1 time
  description: ""
  trigger:
    - platform: homeassistant
      event: start
      id: ventilere1t
  condition: []
  action:
    - service: modbus.write_register
      data:
        hub: hub1
        unit: 1
        value: 3
        address: 100
    - delay:
        hours: 0
        minutes: 59
        seconds: 30
        milliseconds: 0
    - service: modbus.write_register
      data:
        hub: hub1
        unit: 1
        value: 1
        address: 100
  mode: single
- id: "1629231429278"
  alias: Ventilere 8 time3
  description: ""
  trigger:
    - platform: homeassistant
      event: start
  condition: []
  action:
    - service: modbus.write_register
      data:
        hub: hub1
        unit: 1
        address: 100
        value: 2
    - delay:
        hours: 7
        minutes: 59
        seconds: 30
        milliseconds: 0
    - service: modbus.write_register
      data:
        hub: hub1
        unit: 1
        value: 1
        address: 100
  mode: single
- id: "1643135004004"
  alias: Oppdatere villavent luftmengde
  description: ""
  trigger:
    - platform: state
      entity_id: input_number.villavent_luftmengde
  condition: []
  action:
    - service: modbus.write_register
      data:
        hub: hub1
        address: 103
        unit: 1
        value: "{{ trigger.to_state.state | int }}"
    - service: modbus.write_register
      data:
        hub: hub1
        address: 104
        unit: 1
        value: "{{ ((trigger.to_state.state|float) * 0.8) | int }}"
  mode: queued
  max: 10
- id: "1644262815244"
  alias: Dolly OTA Mode
  description: ""
  trigger: []
  condition: []
  action:
    - service: mqtt.publish
      data:
        topic: dolly/ota_mode
        retain: true
        payload: "ON"
        qos: "1"
  mode: single
- id: "1644264630668"
  alias: DollyOTA Mode OFF
  description: ""
  trigger: []
  condition: []
  action:
    - service: mqtt.publish
      data:
        topic: dolly/ota_mode
        retain: true
        payload: "OFF"
    - service: mqtt.publish
      data:
        topic: dolly/sleep_mode
        payload: "ON"
        qos: "0"
  mode: single
- id: "1644683140008"
  alias: Varsle oppvask ferdig
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.oppvaskmaskin_kjorer
      to: "off"
      from: "on"
  condition: []
  action:
    - service: notify.mobile_app_gunnar_s10
      data:
        title: Oppvaskmaskin
        message: Oppvaskmaskina ferdig
    - service: notify.telegramnotification
      data:
        title: "*Oppvaskmaskin*"
        message: Oppvaskmaskina ferdig
  mode: single
- id: "1644683174784"
  alias: Varsle vaskemaskin ferdig
  description: ""
  trigger:
    - platform: state
      to: "off"
      entity_id: binary_sensor.vaskemaskin_kjorer
      from: "on"
  condition: []
  action:
    - service: notify.mobile_app_gunnar_s10
      data:
        title: Vaskemaskin
        message: Vaskemaskina ferdig
    - service: notify.telegramnotification
      data:
        title: "*Vaskemaskin*"
        message: Vaskemaskina ferdig
  mode: single
