# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  trusted_proxies:
    - 10.1.0.0/24
    - 172.30.33.0/28
  use_x_forwarded_for: true

homeassistant:
  packages: !include_dir_merge_named packages/
  allowlist_external_dirs:
    - "/media/snapshots"

folder_watcher:
  - folder: /media/snapshots
    patterns: ["*.jpg", "*.mp4"]

logger:
  default: info
  logs:
    rflink: debug
    homeassistant.components.rflink: debug
    homeassistant.components.zha: debug
    zigpy: debug
